export const PROVINCE_CITY = [
  { "city": "Hà Nội", "province": "Hà Nội" },
  { "city": "Hồ Chí Minh", "province": "TP. Hồ Chí Minh" },
  { "city": "Đà Nẵng", "province": "Đà Nẵng" },
  { "city": "Hải Phòng", "province": "Hải Phòng" },
  { "city": "Cần Thơ", "province": "Cần Thơ" },
  { "city": "Nha Trang", "province": "Khánh Hòa" },
  { "city": "Huế", "province": "Thừa Thiên Huế" },
  { "city": "Vũng Tàu", "province": "Bà Rịa - Vũng Tàu" },
  { "city": "Biên Hòa", "province": "Đồng Nai" },
  { "city": "Buôn Ma Thuột", "province": "Đắk Lắk" },
  { "city": "Đà Lạt", "province": "Lâm Đồng" },
  { "city": "Hạ Long", "province": "Quảng Ninh" },
  { "city": "Pleiku", "province": "Gia Lai" },
  { "city": "Thái Nguyên", "province": "Thái Nguyên" },
  { "city": "Vinh", "province": "Nghệ An" },
  { "city": "Nam Định", "province": "Nam Định" },
  { "city": "Vĩnh Yên", "province": "Vĩnh Phúc" },
  { "city": "Phan Thiết", "province": "Bình Thuận" },
  { "city": "Thủ Dầu Một", "province": "Bình Dương" },
  { "city": "Tuy Hòa", "province": "Phú Yên" },
  { "city": "Rạch Giá", "province": "Kiên Giang" },
  { "city": "Bạc Liêu", "province": "Bạc Liêu" },
  { "city": "Trà Vinh", "province": "Trà Vinh" },
  { "city": "Mỹ Tho", "province": "Tiền Giang" },
  { "city": "Bến Tre", "province": "Bến Tre" },
  { "city": "Cà Mau", "province": "Cà Mau" },
  { "city": "Long Xuyên", "province": "An Giang" },
  { "city": "Châu Đốc", "province": "An Giang" },
  { "city": "Sóc Trăng", "province": "Sóc Trăng" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Điện Biên Phủ", "province": "Điện Biên" },
  { "city": "Lạng Sơn", "province": "Lạng Sơn" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Lai Châu", "province": "Lai Châu" },
  { "city": "Kon Tum", "province": "Kon Tum" },
  { "city": "Tam Kỳ", "province": "Quảng Nam" },
  { "city": "Hội An", "province": "Quảng Nam" },
  { "city": "Quảng Ngãi", "province": "Quảng Ngãi" },
  { "city": "Quảng Trị", "province": "Quảng Trị" },
  { "city": "Đông Hà", "province": "Quảng Trị" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Hà Tĩnh", "province": "Hà Tĩnh" },
  { "city": "Hải Dương", "province": "Hải Dương" },
  { "city": "Hà Nam", "province": "Hà Nam" },
  { "city": "Phủ Lý", "province": "Hà Nam" },
  { "city": "Hòa Bình", "province": "Hòa Bình" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Bắc Giang", "province": "Bắc Giang" },
  { "city": "Bắc Kạn", "province": "Bắc Kạn" },
  { "city": "Tuyên Quang", "province": "Tuyên Quang" },
  { "city": "Cao Bằng", "province": "Cao Bằng" },
  { "city": "Bắc Ninh", "province": "Bắc Ninh" },
  { "city": "Vĩnh Long", "province": "Vĩnh Long" },
  { "city": "Hà Tĩnh", "province": "Hà Tĩnh" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Hậu Giang", "province": "Hậu Giang" },
  { "city": "Quảng Bình", "province": "Quảng Bình" },
  { "city": "Đồng Hới", "province": "Quảng Bình" },
  { "city": "Bình Định", "province": "Bình Định" },
  { "city": "Quy Nhơn", "province": "Bình Định" },
  { "city": "Phú Thọ", "province": "Phú Thọ" },
  { "city": "Việt Trì", "province": "Phú Thọ" },
  { "city": "Ninh Bình", "province": "Ninh Bình" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Bắc Ninh", "province": "Bắc Ninh" },
  { "city": "Uông Bí", "province": "Quảng Ninh" },
  { "city": "Cẩm Phả", "province": "Quảng Ninh" },
  { "city": "Móng Cái", "province": "Quảng Ninh" },
  { "city": "Bắc Giang", "province": "Bắc Giang" },
  { "city": "Bắc Ninh", "province": "Bắc Ninh" },
  { "city": "Tuyên Quang", "province": "Tuyên Quang" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Hòa Bình", "province": "Hòa Bình" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Điện Biên Phủ", "province": "Điện Biên" },
  { "city": "Lai Châu", "province": "Lai Châu" },
  { "city": "Thái Nguyên", "province": "Thái Nguyên" },
  { "city": "Việt Trì", "province": "Phú Thọ" },
  { "city": "Tuyên Quang", "province": "Tuyên Quang" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Phan Rang", "province": "Ninh Thuận" },
  { "city": "Bảo Lộc", "province": "Lâm Đồng" },
  { "city": "Đồng Xoài", "province": "Bình Phước" },
  { "city": "Gia Nghĩa", "province": "Đắk Nông" },
  { "city": "Đông Hà", "province": "Quảng Trị" },
  { "city": "Hội An", "province": "Quảng Nam" },
  { "city": "Tam Kỳ", "province": "Quảng Nam" },
  { "city": "Quảng Ngãi", "province": "Quảng Ngãi" },
  { "city": "Nha Trang", "province": "Khánh Hòa" },
  { "city": "Cam Ranh", "province": "Khánh Hòa" },
  { "city": "Phan Thiết", "province": "Bình Thuận" },
  { "city": "Phan Rang", "province": "Ninh Thuận" },
  { "city": "Phú Quốc", "province": "Kiên Giang" },
  { "city": "Rạch Giá", "province": "Kiên Giang" },
  { "city": "Vĩnh Long", "province": "Vĩnh Long" },
  { "city": "Sa Đéc", "province": "Đồng Tháp" },
  { "city": "Cao Lãnh", "province": "Đồng Tháp" },
  { "city": "Vĩnh Yên", "province": "Vĩnh Phúc" },
  { "city": "Tam Điệp", "province": "Ninh Bình" },
  { "city": "Hà Tiên", "province": "Kiên Giang" },
  { "city": "Bến Tre", "province": "Bến Tre" },
  { "city": "Thủ Dầu Một", "province": "Bình Dương" },
  { "city": "Dĩ An", "province": "Bình Dương" },
  { "city": "Thuận An", "province": "Bình Dương" },
  { "city": "Tân An", "province": "Long An" },
  { "city": "Bạc Liêu", "province": "Bạc Liêu" },
  { "city": "Cà Mau", "province": "Cà Mau" },
  { "city": "Bắc Kạn", "province": "Bắc Kạn" },
  { "city": "Cao Bằng", "province": "Cao Bằng" },
  { "city": "Lạng Sơn", "province": "Lạng Sơn" },
  { "city": "Hà Nam", "province": "Hà Nam" },
  { "city": "Phủ Lý", "province": "Hà Nam" },
  { "city": "Bắc Ninh", "province": "Bắc Ninh" },
  { "city": "Bắc Giang", "province": "Bắc Giang" },
  { "city": "Hải Dương", "province": "Hải Dương" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Hạ Long", "province": "Quảng Ninh" },
  { "city": "Cẩm Phả", "province": "Quảng Ninh" },
  { "city": "Móng Cái", "province": "Quảng Ninh" },
  { "city": "Uông Bí", "province": "Quảng Ninh" },
  { "city": "Hòa Bình", "province": "Hòa Bình" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Điện Biên Phủ", "province": "Điện Biên" },
  { "city": "Lai Châu", "province": "Lai Châu" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Ninh Bình", "province": "Ninh Bình" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Hà Nội", "province": "Hà Nội" },
  { "city": "Hải Phòng", "province": "Hải Phòng" },
  { "city": "Hà Nam", "province": "Hà Nam" },
  { "city": "Phủ Lý", "province": "Hà Nam" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Nam Định", "province": "Nam Định" },
  { "city": "Phan Rang", "province": "Ninh Thuận" },
  { "city": "Phan Thiết", "province": "Bình Thuận" },
  { "city": "Cam Ranh", "province": "Khánh Hòa" },
  { "city": "Quy Nhơn", "province": "Bình Định" },
  { "city": "Đồng Hới", "province": "Quảng Bình" },
  { "city": "Đông Hà", "province": "Quảng Trị" },
  { "city": "Hà Tĩnh", "province": "Hà Tĩnh" },
  { "city": "Huế", "province": "Thừa Thiên Huế" },
  { "city": "Đà Nẵng", "province": "Đà Nẵng" },
  { "city": "Tam Kỳ", "province": "Quảng Nam" },
  { "city": "Hội An", "province": "Quảng Nam" },
  { "city": "Quảng Ngãi", "province": "Quảng Ngãi" },
  { "city": "Pleiku", "province": "Gia Lai" },
  { "city": "Kon Tum", "province": "Kon Tum" },
  { "city": "Buôn Ma Thuột", "province": "Đắk Lắk" },
  { "city": "Gia Nghĩa", "province": "Đắk Nông" },
  { "city": "Đà Lạt", "province": "Lâm Đồng" },
  { "city": "Bảo Lộc", "province": "Lâm Đồng" },
  { "city": "Bà Rịa", "province": "Bà Rịa - Vũng Tàu" },
  { "city": "Vũng Tàu", "province": "Bà Rịa - Vũng Tàu" },
  { "city": "Long Xuyên", "province": "An Giang" },
  { "city": "Châu Đốc", "province": "An Giang" },
  { "city": "Cao Lãnh", "province": "Đồng Tháp" },
  { "city": "Sa Đéc", "province": "Đồng Tháp" },
  { "city": "Rạch Giá", "province": "Kiên Giang" },
  { "city": "Hà Tiên", "province": "Kiên Giang" },
  { "city": "Cà Mau", "province": "Cà Mau" },
  { "city": "Bạc Liêu", "province": "Bạc Liêu" },
  { "city": "Sóc Trăng", "province": "Sóc Trăng" },
  { "city": "Trà Vinh", "province": "Trà Vinh" },
  { "city": "Vĩnh Long", "province": "Vĩnh Long" },
  { "city": "Mỹ Tho", "province": "Tiền Giang" },
  { "city": "Bến Tre", "province": "Bến Tre" },
  { "city": "Tân An", "province": "Long An" },
  { "city": "Thủ Dầu Một", "province": "Bình Dương" },
  { "city": "Đồng Xoài", "province": "Bình Phước" },
  { "city": "Vĩnh Yên", "province": "Vĩnh Phúc" },
  { "city": "Phúc Yên", "province": "Vĩnh Phúc" },
  { "city": "Bắc Giang", "province": "Bắc Giang" },
  { "city": "Bắc Kạn", "province": "Bắc Kạn" },
  { "city": "Lạng Sơn", "province": "Lạng Sơn" },
  { "city": "Cao Bằng", "province": "Cao Bằng" },
  { "city": "Phủ Lý", "province": "Hà Nam" },
  { "city": "Bắc Ninh", "province": "Bắc Ninh" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Điện Biên Phủ", "province": "Điện Biên" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Lai Châu", "province": "Lai Châu" },
  { "city": "Hạ Long", "province": "Quảng Ninh" },
  { "city": "Uông Bí", "province": "Quảng Ninh" },
  { "city": "Cẩm Phả", "province": "Quảng Ninh" },
  { "city": "Móng Cái", "province": "Quảng Ninh" },
  { "city": "Hòa Bình", "province": "Hòa Bình" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Điện Biên Phủ", "province": "Điện Biên" },
  { "city": "Lai Châu", "province": "Lai Châu" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Ninh Bình", "province": "Ninh Bình" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Hà Nội", "province": "Hà Nội" },
  { "city": "Hải Phòng", "province": "Hải Phòng" },
  { "city": "Hà Nam", "province": "Hà Nam" },
  { "city": "Phủ Lý", "province": "Hà Nam" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Nam Định", "province": "Nam Định" },
  { "city": "Bắc Giang", "province": "Bắc Giang" },
  { "city": "Bắc Ninh", "province": "Bắc Ninh" },
  { "city": "Tuyên Quang", "province": "Tuyên Quang" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Hòa Bình", "province": "Hòa Bình" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Điện Biên Phủ", "province": "Điện Biên" },
  { "city": "Lai Châu", "province": "Lai Châu" },
  { "city": "Thái Nguyên", "province": "Thái Nguyên" },
  { "city": "Việt Trì", "province": "Phú Thọ" },
  { "city": "Tuyên Quang", "province": "Tuyên Quang" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Lào Cai", "province": "Lào Cai" },
  { "city": "Hà Giang", "province": "Hà Giang" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Hưng Yên", "province": "Hưng Yên" },
  { "city": "Phú Thọ", "province": "Phú Thọ" },
  { "city": "Phú Yên", "province": "Phú Yên" },
  { "city": "Quảng Nam", "province": "Quảng Nam" },
  { "city": "Quảng Ngãi", "province": "Quảng Ngãi" },
  { "city": "Quảng Ninh", "province": "Quảng Ninh" },
  { "city": "Quảng Trị", "province": "Quảng Trị" },
  { "city": "Sóc Trăng", "province": "Sóc Trăng" },
  { "city": "Sơn La", "province": "Sơn La" },
  { "city": "Tây Ninh", "province": "Tây Ninh" },
  { "city": "Thái Bình", "province": "Thái Bình" },
  { "city": "Thái Nguyên", "province": "Thái Nguyên" },
  { "city": "Thanh Hóa", "province": "Thanh Hóa" },
  { "city": "Huế", "province": "Thừa Thiên Huế" },
  { "city": "Tiền Giang", "province": "Tiền Giang" },
  { "city": "Trà Vinh", "province": "Trà Vinh" },
  { "city": "Tuyên Quang", "province": "Tuyên Quang" },
  { "city": "Vĩnh Long", "province": "Vĩnh Long" },
  { "city": "Vĩnh Phúc", "province": "Vĩnh Phúc" },
  { "city": "Yên Bái", "province": "Yên Bái" },
  { "city": "Thái Nguyên", "province": "Thái Nguyên" },
  { "city": "Vĩnh Phúc", "province": "Vĩnh Phúc" }
];

export function GetUniqueProvinceCity() {
  const uniqueCities = new Set();
  return PROVINCE_CITY.filter(item => {
    const isDuplicate = uniqueCities.has(item.city);
    uniqueCities.add(item.city);
    return !isDuplicate;
  });
}

export const LOCALSTORAGE_USER_STORE = "user store";
export const LOCALSTORAGE_CART_STORE = "cart store";
